--liquibase formatted sql
--changeset evgenii:202404290000.init_schema.sql

CREATE TABLE IF NOT EXISTS classes (
    id bigint PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    class_name varchar NOT NULL,
    package_name varchar NOT NULL,
    UNIQUE (class_name, package_name)
);

CREATE INDEX idx_package_name ON classes(package_name);

CREATE TABLE IF NOT EXISTS method_executions (
    id bigint PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    class_id bigint,
    method_name varchar NOT NULL,
    execution_time bigint NOT NULL,
    created timestamp with time zone NOT NULL,
    FOREIGN KEY (class_id) REFERENCES classes(id)
);

CREATE INDEX idx_class_id ON method_executions(class_id);
